### ISSUE TITLE
Please  How the contract works ?

### ISSUE THREAD

**Issue by christianxiao** [celer-network/cBridge-contracts#10]
for example, in ```transferOut```  why we need 
```
 IERC20(_token).safeTransferFrom(msg.sender, address(this), _amount);
```

**Comment by zhangqi021** [comment]
The `_transfer` function is called to send tokens from msg sender to hash lock.

You know, if tokens need to be bridged between 2 chains, we will have to deploy 2 contracts on these 2 chains.
A success process of bridge is that:
1. the user transfers tokens out to hash lock on chain 1
2. the relayNode transfers tokens in to hash lock on chain 2. 
3. the user confirms, and sends tokens from hash lock to the relayNode on chain 1.
4. the relayNode confirms, and sends tokens from hash lock to the user on chain 2.
The 1st step is the `transferOut` and 2nd step is the `transferIn`. Both of them are calling the `_transfer` function to send tokens to hash lock.
